- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: Obtener comando de token
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Guardar comando token en variable join_command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }} "


- hosts: workers
  become: yes
  tasks:
    - name: Añadir a cluster
      shell: "{{ hostvars['masters'].join_command }}"
